### ISSUE TITLE
KeyError: 'RepetitionTime' in version 1.3.0

### ISSUE THREAD

**Issue by Shengjie0813** [poldracklab/fmriprep#1516] opened 2019-02-25 10:25 UTC
Hi all,
I am testing using fMRIprep to preprocess my fMRI data. In my first try, everything looks good. But today, when I ran them again, I met the problem related to RepetitionTime. The key 'RepetitionTime' is present in the .json file. I searched this question, and found some people have the same problem in older version. I followed suggestions in their post but still cannot figure it out. Here is my traceback information:

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 751, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 218, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err,
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 516, in init_single_subject_wf
    num_bold=len(subject_data['bold']))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 683, in init_func_preproc_wf
    name='carpetplot_wf')
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/confounds.py", line 370, in init_carpetplot_wf
    tr=metadata['RepetitionTime'],
KeyError: 'RepetitionTime'
fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

My data passed BIDS validator:
This dataset appears to be BIDS compatible.
        Summary:                 Available Tasks:        Available Modalities: 
        800 Files, 2.46GB        fMRI_test               T1w                   
        1 - Subject                                                  bold                  
        1 - Session                                                 events                
                                                                           fieldmap     

I also tried:
find $BIDS_DIR -name ‘_bold.’
find $BIDS_DIR -name ‘*_bold.json’ -exec grep RepetitionTime “{}” +
and can get related information. So I am guessing, is it because 'RepetitionTime' cannot be recognized by fMRIPrep?

**Comment by oesteban** [comment] 2019-03-14 02:06
Hi @Shengjie0813, do you have any dataset you can share so that we can replicate this issue? Is this issue a duplicate of https://neurostars.org/t/keyerror-repetitiontime-in-version-1-3-0-post2-and-filedsmap-data-are-not-recognized-by-fmriprep/3671 (and therefore it has been fixed)?

**Comment by Shengjie0813** [comment] 2019-03-14 05:02
Sorry for my late reply. Yes, they are the same problem and already solved. Thank you for your help!

**Closed** 2019-03-14 05:37 UTC
Labels: bug
