### ISSUE TITLE
Poor BOLD-T1w coregistration in ds000108

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#908] opened 2017-12-19 23:07 UTC
![image](https://user-images.githubusercontent.com/238759/34183146-298a7062-e4ce-11e7-9a66-6b6c498096e4.png)

Could be related to SyN-SDC which was applied.

sub-03_task-Emotionregulation_run-01

**Comment by oesteban** [comment] 2017-12-19 23:58
Mmm maybe I'm wrong but SyN-SDC is not used here, it is just generated for us to check if it worked. Correct @effigies ?

**Comment by oesteban** [comment] 2018-02-15 23:32
This looks better:

![ds108-sub-03-bbr](https://user-images.githubusercontent.com/598470/36286579-3d47d33c-1265-11e8-860f-9156ff34f12d.png)

SyN-SDC performed much better. However, I bet this BOLD dataset has an X-flip.

The report shows the xform warning:

> **WARNING - Missing orientation information**
> FMRIPREP could not retrieve orientation information from the image header. The qform and sform matrices have been set to a default, LAS-oriented affine. Analyses of this dataset MAY BE INVALID.

**Comment by oesteban** [comment] 2018-03-01 04:31
Duplicate of #988

**Closed by oesteban** 2018-03-01 04:31 UTC
Labels: coregistration, ds000108, phase 2 findings
