### ISSUE TITLE
grand mean intensity normalization / global rescaling

### ISSUE THREAD

**Issue by ilyaveer** [poldracklab/fmriprep#1642] opened 2019-05-20 08:31 UTC
Hi fmriprep developers,

In the docs I couldn't find any reference to grand mean intensity normalization being applied to the BOLD data, which is a necessary step to calculate valid group statistics later on. Perhaps this is something that could be added, or is this already being done under the hood in the current version?

Cheers,
Ilya

**Comment by oesteban** [comment] 2019-05-20 16:11
Duplicate of #1210. Please follow up there.

Thanks for requesting!

**Closed by oesteban** 2019-05-20 16:11 UTC
