### ISSUE TITLE
FLIRT BBR error: short header read

### ISSUE THREAD

**Issue by jawaltz** [poldracklab/fmriprep#2235] opened 2020-08-10 17:18 UTC
Hi-

I have 3 data sets for which fmriprep didn't finish cleanly. There are error messages at the bottom of the html reports, and I was wondering if I could have one of you explain them to me. It is hard for me to know what they mean, and how important they are. It appears that intact structural and functional images exist for some, but I would like to know if they are usable. The 3 data sets are attached here.

Thanks,

Jim Waltz
University of Maryland School of Medicine

[DataSetsWithErrors.zip](https://github.com/poldracklab/fmriprep/files/5052294/DataSetsWithErrors.zip)

---

fMRIPrep version: 20.0.2

**Comment by effigies** [comment] 2020-08-10 17:23
This looks like a duplicate of #1920, and in the past, it has seemed to result from a filesystem synchronization issue. What is your `/work` filesystem?

**Comment by jawaltz** [comment] 2020-08-10 17:54
Ah yes. I had to correct my work directory, to specify a drive with more space, and it is possible that those analyses were referencing old work directories, which were either incomplete or gone. Let me try to delete all references to those subjects in work directories and re-run. Thank you,

**Comment by jawaltz** [comment] 2020-08-11 16:08
Delete all references to those subjects in work directories caused fmriprep to finish without errors. Thanks for your quick response.

**Comment by mgxd** [comment] 2020-08-11 16:23
Glad you were able to fix the problem!

**Closed by mgxd** 2020-08-11 16:23 UTC
Labels: question
