### ISSUE TITLE
tcompcor error

### ISSUE THREAD

**Issue by shanaahall** [poldracklab/fmriprep#2155] opened 2020-05-29 18:38 UTC
For your bug report, include this information:
-------------------------
What version of fMRIPrep are you using? 1.5.1
What were you trying to do? Run a participant through fmriprep 
What did you expect will happen? Fully processed data, including confounds file
What actually happened? No confound file was produced. 
Can you replicate the behavior? If yes, how? Reran this participant multiple times with the same error. I tried using the --low-mem flag, as advised for others who had this problem, but it did not help.

List the steps you performed that revealed the bug to you. The report said that there was an error with the tcompcor node. 
Include any code samples. Enclose them in triple back-ticks (```)

The error message in the report is 
```
Node Name: fmriprep_wf.single_subject_01088_wf.func_preproc_ses_baseline_task_rest_acq_ppgresp_run_01_wf.bold_confounds_wf.tcompcor
Node Name: fmriprep_wf.single_subject_01088_wf.func_preproc_ses_baseline_task_rest_acq_ppgresp_run_02_wf.bold_confounds_wf.tcompcor
```

The crash log says:
```
Node: fmriprep_wf.single_subject_01088_wf.func_preproc_ses_baseline_task_rest_acq_ppgresp_run_01_wf.bold_confounds_wf.tcompcor
Working directory: /mnt/munin/Meade/ConnNeuro.01/Analysis/BIDS/fmriprep_workingdir/fmriprep_wf/single_subject_01088_wf/func_preproc_ses_baseline_task_rest_acq_ppgresp_run_01_wf/bold_confounds_wf/tcompcor

Node inputs:

components_file = tcompcor.tsv
failure_mode = NaN
header_prefix = t_comp_cor_
high_pass_cutoff = 128.0
ignore_initial_volumes = 0
mask_files = <undefined>
mask_index = <undefined>
mask_names = <undefined>
merge_method = <undefined>
num_components = <undefined>
percentile_threshold = 0.05
pre_filter = cosine
realigned_file = <undefined>
regress_poly_degree = 1
repetition_time = 1.5
save_metadata = True
save_pre_filter = True
use_regress_poly = <undefined>
variance_threshold = 0.5

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 479, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 569, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 662, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 382, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/patches.py", line 51, in _run_interface
    runtime = super(RobustTCompCor, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/algorithms/confounds.py", line 560, in _run_interface
    mask_images = self._process_masks(mask_images, imgseries.get_data())
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/algorithms/confounds.py", line 760, in _process_masks
    (1. - self.inputs.percentile_threshold)).astype(int))
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3540, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3652, in _quantile_unchecked
    interpolation=interpolation)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3250, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3767, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 181, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

```

and in the output file, after the aroma node, it says: 

```
200528-22:40:08,539 nipype.workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_01088_wf.func_preproc_ses_baseline_task_rest_acq_ppgresp_run_01_wf.bold_confounds_wf.tcompcor
200528-22:40:08,544 nipype.workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_01088_wf.func_preproc_ses_baseline_task_rest_acq_ppgresp_run_02_wf.bold_confounds_wf.tcompcor
fMRIPrep failed: Workflow did not execute cleanly. Check log for details
Preprocessing did not finish successfully. Errors occurred while processing data from participants: 01088 (2). Check the HTML reports for details.
/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/images.py:725: RuntimeWarning: Mean of empty slice.
  series[:, j] = data[mask, :].mean(axis=0)
/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/images.py:725: RuntimeWarning: Mean of empty slice.
  series[:, j] = data[mask, :].mean(axis=0)
/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/_methods.py:78: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/usr/local/miniconda/lib/python3.7/site-packages/scipy/fftpack/basic.py:160: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z[index] = x
/usr/local/miniconda/lib/python3.7/site-packages/nipype/algorithms/confounds.py:1099: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.7/site-packages/nipype/algorithms/confounds.py:1099: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.7/site-packages/scipy/fftpack/basic.py:160: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z[index] = x
/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py:513: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  maximum_intensity_data = data[inds]
/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py:513: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  maximum_intensity_data = data[inds]

```

**Comment by shanaahall** [comment] 2020-06-01 01:35
Update: I just tried it with version 1.5.9 and got the same error.

**Comment by oesteban** [comment] 2020-06-01 06:35
Yeah, I don't think we included any specific fix for this kind of problem (or related) between 1.5.1 and 1.5.9.

I'm really puzzled by this entry on your crashfile:
```
realigned_file = <undefined>
```
[how's that possible?](https://github.com/nipy/nipype/blob/4c48a185e4d190071f78a6766ca34c71ff61e10f/nipype/algorithms/confounds.py#L390)

Did you get a report for this subject?

**Comment by shanaahall** [comment] 2020-06-01 13:46
Hm. Strange. I did get a report for them. What should I look for or send you?

**Comment by mgxd** [comment] 2020-06-01 14:03
@shanaahall are you tied to the `1.5.x` series, or could you try with the latest release and see if you are still encountering the issue? 

Also for reference, related issues:
https://github.com/poldracklab/fmriprep/issues/1409 https://github.com/poldracklab/fmriprep/issues/1697

I'm not sure whether or not this has already been solved

**Comment by shanaahall** [comment] 2020-06-01 14:40
I should be able to try with the latest release. Hopefully that will fix it. Upon looking further, it seems that something is happening with the csf mask. In the working directory, the csf_roi file is blank and I just discovered another subject who ran to completion but in the confounds file, the csv columns were NAs. So I'll see if the new fmriprep version works.

**Comment by oesteban** [comment] 2020-06-01 16:20
This is probably a duplicate of #1409, but the `<undefined>` mandatory fields in the crashfile make me quite disoriented. There could be an issue with how you are particularly running fMRIPrep (some race condition between parallel runs, filesystem access problems... IDK).

In the reports, if you can't share one failing example, I would look into the "BOLD ROIs" plot, and see whether there is a blue contour (delineating the tCompCor mask). You could just upload one of those svg files.

**Comment by shanaahall** [comment] 2020-06-01 17:59
Hm. Those plots were not created. Must have bugged before that, I guess? It just created the aroma_bold.svg, bbregister_bold.svg, and sdc_bold.svg. I'll let you know what happens with the fmriprep 20.1.0.

**Comment by oesteban** [comment] 2020-06-01 18:01
> Must have bugged before that, I guess?

Surely. Do you have access to the full output log from fMRIPrep?

**Comment by shanaahall** [comment] 2020-06-01 18:10
Yes. Here it is. 


[Output-sub-01088fmriprep.txt](https://github.com/poldracklab/fmriprep/files/4712786/Output-sub-01088fmriprep.txt)

**Comment by oesteban** [comment] 2020-06-01 18:19
Okay, there are a couple of weird things in the log.

1) It seems to contain 5 concatenated runs of fMRIPrep on the same single subject, the first back in Jan 31, 2020 and then the last 3 during last week. The one thing that surprised me is that the BIDS validator did not seem to find the same amounts of data in the input folder.

2) The validator identified two tasks (rest1, rest2), but fMRIPrep is processing different tasks (rest).

Do you know why this could be happening?

**Comment by shanaahall** [comment] 2020-06-02 00:38
Version 20.1.0 finished and I'm still getting the error with the tcompcor node. I have been deleting the working directory and the fmriprep directories every time I run a new test, but I'm leaving the freesurfer directory in place because it seems to be fine and I was trying to save time. But could this be causing problems? When I was testing several months ago, I tried deleting the freesurfer directory before the new test but that did not help.

1. It must just be appending the logs onto the existing log file every time ti try to rerun fmriprep. It looks like there are different amounts of data in various trials because most subjects ran successfully and then I deleted their BIDS formatted data, to save space on the server.

2. That is strange. I looked at another log file for other subjects who finished successfully and the validator is also calling them rest1 and rest2 but the task name in the BIDS formatted files is always just rest. And I just ran the validator from its website and it is also calling them rest1 and rest2 but in the description of the warnings, it is recognizing that the files are named with the 'task-rest' and the 'run-01' convention. So it doesn't seem like this is a problem but maybe so if this is not standard? I don't know why that would cause problems is this one person but not the others. 

I'm attaching the log file with the info from the new test with version 20.1.0. 
[Output-sub-01088fmriprep.txt](https://github.com/poldracklab/fmriprep/files/4714112/Output-sub-01088fmriprep.txt)

**Comment by shanaahall** [comment] 2020-06-17 17:56
Hello. I just wanted to follow-up with this. Is there anything I can do to help with this? I have compared the data for this participant to data for other participants who ran successfully but did not see any differences. Is it possible I'm missing something?

**Comment by oesteban** [comment] 2020-06-17 18:47
Hi @shanaahall, the most likely reason for the type of error you are getting is that tCompCor is receiving an empty mask. This could happen for two reasons: 1) the bold mask is pretty bad in first place; or 2) the bold mask is very small (e.g., with very narrow FoV images).

We are currently working on a large refactor of the CompCor masks (#2129) targeting release 20.2. I'll give you some directions so that you can test some release candidate on your data and check whether that fixed your issue.

**Comment by mgxd** [comment] 2020-08-05 17:47
Closing this, following up in #2209

**Closed by mgxd** 2020-08-05 17:47 UTC
Labels: bug
