### ISSUE TITLE
workflow error: node acompcor failed to run on host [fmriprep]

### ISSUE THREAD

**Issue by sadevp** [poldracklab/fmriprep#812] opened 2017-11-02 19:55 UTC
Hello,

I received an error for one participant file in this dataset: https://openneuro.org/datasets/ds000009/versions/00002?app=FMRIPREP&version=23&job=e2902b0b-029b-4163-bdad-75418cfd64f9

This caused the newest version of fmriprep to fail on this dataset.

Here is the crash log for that particular subject [07]:

Traceback (most recent call last):
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
result['result'] = node.run(updatehash=updatehash)
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 407, in run
self._run_interface()
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
self._result = self._run_command(execute)
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
result = self._interface.run()
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1088, in run
runtime = self._run_interface(runtime)
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/common/report.py", line 55, in _run_interface
ReportCapableInterface, self)._run_interface(runtime)
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 471, in _run_interface
self.inputs.pre_filter, degree, self.inputs.high_pass_cutoff, TR)
File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 1070, in compute_noise_components
u, _, _ = linalg.svd(M, full_matrices=False)
File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py", line 119, in svd
raise LinAlgError("SVD did not converge")
numpy.linalg.linalg.LinAlgError: SVD did not converge

**Comment by effigies** [comment] 2017-11-02 20:08
Duplicate of #776. Should be resolved by #807, which will be in the next release.

**Closed by effigies** 2017-11-02 20:08 UTC
