### ISSUE TITLE
nipype set up error report

### ISSUE THREAD

**Issue by 0zonebilly** [poldracklab/fmriprep#1209] opened 2018-07-18 01:03 UTC
[Node] Setting-up "fmriprep_wf.single_subject_1_wf.func_preproc_task_rest_acq_TR2500TE24_wf.bold_confounds_wf.signals" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_1_wf/func_preproc_task_rest_acq_TR2500TE24_wf/bold_confounds_wf/signals".

180717-13:22:59,945 nipype.workflow INFO:
	 [Node] Running "signals" ("nipype.interfaces.nilearn.SignalExtraction")
exception calling callback for <Future at 0x7f9919494e48 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x7f99194a4860 state=finished raised BrokenProcessPool>

**Comment by oesteban** [comment] 2018-07-18 03:43
Looks like a duplicate of #1207 - very likely fmriprep exceeded the memory limits

**Comment by effigies** [comment] 2018-07-26 19:42
If it's failing on `SignalExtraction`, it's almost certainly memory. Try using `--low-mem`.

We should probably try to catch `BrokenProcessPool` exceptions and make that clearer that it was very likely a memory issue.

**Comment by oesteban** [comment] 2018-08-02 16:04
Hi @0zonebilly, we have addressed this issue and attempted to fix it with 1.1.3. Could you try that last version of fmriprep and reopen this issue if the memory error is still happening?

**Closed by oesteban** 2018-08-02 16:04 UTC
Labels: bug
