### ISSUE TITLE
No confounds file due to IndexError for tcompcor 

### ISSUE THREAD

**Issue by zenkavi** [poldracklab/fmriprep#1697] opened 2019-07-09 22:05 UTC
The following error resulted in not having a confounds file for that run of the subject. Everything else looked fine but I might be missing something.

```
Node Name: fmriprep_wf.single_subject_100068_wf.func_preproc_task_machinegame_run_001_wf.bold_confounds_wf.tcompcor
File: /oak/stanford/groups/russpold/data/ds000054/0.0.4/derivatives/fmriprep_1.4.0/fmriprep/sub-100068/log/20190704-092934_a41c660f-f278-453c-b0f6-56dc37edc4bb/crash-20190704-200938-zenkavi-tcompcor-34a37fb7-b906-4389-8d3f-3dee188531cc.txt
Working Directory: /tmp/work/fmriprep_wf/single_subject_100068_wf/func_preproc_task_machinegame_run_001_wf/bold_confounds_wf/tcompcor
Inputs: 
components_file: tcompcor.tsv
failure_mode: NaN
header_prefix: t_comp_cor_
high_pass_cutoff: 128.0
ignore_initial_volumes: 1
mask_files: ['/tmp/work/fmriprep_wf/single_subject_100068_wf/func_preproc_task_machinegame_run_001_wf/bold_confounds_wf/tcc_tfm/sub-100068_T1w_corrected_xform_rbrainmask_eroded_trans_boldmsk.nii.gz']
mask_index:
mask_names:
merge_method:
num_components:
percentile_threshold: 0.05
pre_filter: cosine
realigned_file: /tmp/work/fmriprep_wf/single_subject_100068_wf/func_preproc_task_machinegame_run_001_wf/bold_bold_trans_wf/merge/vol0000_xform-00000_merged.nii.gz
regress_poly_degree: 1
repetition_time: 1.0
save_metadata: True
save_pre_filter: True
use_regress_poly:
variance_threshold: 0.5
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 375, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/patches.py", line 51, in _run_interface
    runtime = super(RobustTCompCor, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/algorithms/confounds.py", line 560, in _run_interface
    mask_images = self._process_masks(mask_images, imgseries.get_data())
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/algorithms/confounds.py", line 760, in _process_masks
    (1. - self.inputs.percentile_threshold)).astype(int))
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3540, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3652, in _quantile_unchecked
    interpolation=interpolation)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3250, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3767, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 181, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```

**Comment by jeroenvanbaar** [comment] 2019-10-11 15:40
I'm also missing confounds files for some subjects. As far as I can tell, however, all the confounds are written to the working directory (I've looked specifically at the realignment parameters and framewise displacement). Here is the crash log for this component:

[crash-20191011-015931-jvanbaar-merge_confound_metadata-224ef30b-5a7f-43ef-b8f0-50c3a2f9167d.txt](https://github.com/poldracklab/fmriprep/files/3718387/crash-20191011-015931-jvanbaar-merge_confound_metadata-224ef30b-5a7f-43ef-b8f0-50c3a2f9167d.txt)

Key lines:

```
Node: fmriprep_wf.single_subject_002_wf.func_preproc_ses_1_task_wordReading_run_4_wf.bold_confounds_wf.merge_confound_metadata
Working directory: /s1/sub-002/fmriprep_wf/single_subject_002_wf/func_preproc_ses_1_task_wordReading_run_4_wf/bold_confounds_wf/merge_confound_metadata

Node inputs:

axis = vstack
in1 = {'t_comp_cor_00': {'SingularValue': 143.4811869774, 'VarianceExplained': 0.1847431329, 'CumulativeVarianceExplained': 0.1847431329, 'Retained': True, 'Method': 'tCompCor'}, 't_comp_cor_01': {'SingularValue': 

[...]

{'Mask': 'WM', 'SingularValue': 0.0, 'VarianceExplained': 0.0, 'CumulativeVarianceExplained': 1.0, 'Retained': False, 'Method': 'aCompCor'}}
no_flatten = False
ravel_inputs = False

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 488, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 152, in write_report
    result = node.result  # Locally cache result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 198, in result
    op.join(self.output_dir(), 'result_%s.pklz' % self.name))[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 300, in load_resultfile
    result = loadpkl(results_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 687, in loadpkl
    pkl_file = pklopen(infile.name, 'rb')
  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/local/miniconda/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'result_merge_confound_metadata.pklz'
```

Strangely the file 'result_merge_confound_metadata.pklz' does exist in my working dir.

**Comment by oesteban** [comment] 2019-10-15 20:54
@jeroenvanbaar I'm quite positive this is a different error - please follow up on #1819.

@rciric, how are we doing with respect to the original issue?

**Comment by oesteban** [comment] 2020-05-20 17:46
- I have re-run this subject without issues.
- Re-running led me to think about the nipype issue linked above, to discovering https://github.com/poldracklab/smriprep/issues/189 and then to filing #2129.

I'm closing this as the root cause of it seems to have been addressed.

**Closed by oesteban** 2020-05-20 17:46 UTC
Labels: bug, confounds, effort: medium, impact: medium
