### ISSUE TITLE
Suggested: html iframe for manual QC of fmriprep report

### ISSUE THREAD

**Issue by dorianps** [poldracklab/fmriprep#1948] opened 2020-01-23 17:11 UTC
Not sure whether anybody has done anything in this regard, but we currently need to manually inspect all fmriprep reports to get manual assessments of quality controls. We had planned to do this with a bash script in command line, but is way too ugly for proper usability. I am thinking that the best way to do a report is to put the html file in an iFrame and have another frame with score sheets, checkboxes, etc. to get inputs from the rater. This is mostly inspired by what I saw in MRIQC (although I don't like the floating concepts that overlaps with results).

Is this something anybody has thought about, or perhaps worth considering to include in fmriprep in the future?

My knowledge on html is a bit rusty and I remember POST requests need a webserver, so I don't know how MRIQC does it, but an integrated html frame would be the easiest solution I can think to rate data quality based on fmriprep outputs.

**Comment by oesteban** [comment] 2020-01-28 08:01
I think this is a duplicate of #1910. Please follow up there (or reopen this issue if it is not the same feature being proposed).

**Closed by oesteban** 2020-01-28 08:01 UTC

**Comment by dorianps** [comment] 2020-01-28 14:54
Fyi, we are looking into making this possible with in-house code, but I wanted to share some thoughts on this process.
1. The floating widget could be a problem when assessing quality because it overlaps with the page.
2. It would be better if QC is flexible to the user needs. Someone may only want to QC sdc, someone else template registrations, AROMA, etc. A fixed solution for everyone may become a problem. The ideal solution would be a template selection on what the user wants to QC.
3. Saving the file from the widget is a big problem. Browsers would just save files in Downloads, while a proper QC script needs to save files in the respective subject folder. Not sure how to overcome this, we are looking into what can be done.
4. QC formats are not standard, but we have developed a format we hope to use for all our data, an example for segmentation data is here: https://github.com/bids-standard/bids-specification/issues/353 . There is no standard for this, but we felt we need to capture multiple ratings from each rater, and multiple raters, as well as details of the ratings. Short story, it would be ideal if the json file is flexible, or uses a user defined template, which I know is very hard to do.

**Comment by oesteban** [comment] 2020-01-28 21:12
> Fyi, we are looking into making this possible with in-house code, but I wanted to share some thoughts on this process.

Happy to assist on this.

> 1. The floating widget could be a problem when assessing quality because it overlaps with the page.

Well, that's very MRIQC specific - we don't fix that solution within #1910. And, even in MRIQC, you can always put it away (close it) and reopen it when finalizing the rating.

> 2. It would be better if QC is flexible to the user needs. Someone may only want to QC sdc, someone else template registrations, AROMA, etc. A fixed solution for everyone may become a problem. The ideal solution would be a template selection on what the user wants to QC.

I guess allowing to have missing fields would suffice here.

> 3. Saving the file from the widget is a big problem. Browsers would just save files in Downloads, while a proper QC script needs to save files in the respective subject folder. Not sure how to overcome this, we are looking into what can be done.

There are two options here: cookies and the MRIQC Web-API

> 4. QC formats are not standard, but we have developed a format we hope to use for all our data, an example for segmentation data is here: [bids-standard/bids-specification#353](https://github.com/bids-standard/bids-specification/issues/353) . There is no standard for this, but we felt we need to capture multiple ratings from each rater, and multiple raters, as well as details of the ratings. Short story, it would be ideal if the json file is flexible, or uses a user defined template, which I know is very hard to do.

I would dissociate QC of fMRIPrep from the suggestion to BIDS you made. I would see it is reasonable to be able to include some quality annotations about the ACQUIRED data, but as regards preprocessing, BIDS-Derivatives is pretty liberal as to how you should write the outputs of your pipeline (understanding this qc process as just another pipeline on top of fMRIPrep).

**Comment by dorianps** [comment] 2020-01-28 22:12
cool, we can keep in touch about this idea. The only thing that I am concerned with is the lack of standard in naming fields in the QC process. I can use RaterName as a field while you can use RaterID. However, if there some effort to coordinate on some basic fields of QC there is a chance that the standard can be adopted by more people later.

P.s. My proposed structure at the link above was born from the need to assess Freesurfer segmentations, not raw BIDS data. It is not different than what will be needed for fmriprep, except that a json set of ratings for fmriprep could have something like SDC-fmb: 3, SYN-sdc: 0, TemplateRegistrations{ [template1 {RegistrationQuality: 1}, template2{RegistrationQuality: 3}] }: 1, etc.
