### ISSUE TITLE
Skull stripping failure

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#552] opened 2017-06-09 17:01 UTC
![image](https://user-images.githubusercontent.com/238759/26985852-30e45880-4cfa-11e7-89f3-f5c509b88099.png)

https://neurostars.org/t/what-to-do-when-fmriprep-goes-wrong/508

**Comment by chrisfilo** [comment] 2017-06-09 17:03
https://sourceforge.net/p/advants/discussion/840261/thread/3fc8296f/#fcad

**Comment by chrisfilo** [comment] 2017-06-10 07:59
Wisdom from Nick:
"I would use the NKI template and pad the image by 20 voxels at least in the front."

**Comment by oesteban** [comment] 2017-06-10 18:27
Even if we get a decent outline of the brain on the right side of the image, what will happen in further registration steps? Will that expand the mask to the bit lost in the posterior extreme of the volume?

**Comment by chrisfilo** [comment] 2017-06-10 18:35
I don't think the goal is to extend the mask into the padding, but create an accurate mask that only included brain tissue. 

BTW This might seem like an edge case, but it could be a good proxy for limited field of view acquisitions.

**Comment by oesteban** [comment] 2017-11-10 23:45
This a duplicate of #730 - (this is "atypical" for the wrap around artifact, but atypical nonetheless).

**Closed by oesteban** 2017-11-10 23:45 UTC
