### ISSUE TITLE
Race condition: FreeSurfer setup node run in multiple processes simultaneously

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#772] opened 2017-10-17 18:54 UTC
This is a bit of a two-part problem:

1) If the working directory is shared, this becomes a nipype problem, where two separate processes (possibly on two separate compute nodes using a potentially slow-to-sync filesystem) could try to create the same node directory.
2) Whatever the working directory issue, if the output directory is shared, then we should figure out some way for competing processes to decide on winner that gets to copy the files over.

Spawned by report here: https://neurostars.org/t/fmriprep-errors-and-error-recovery/901

**Comment by oesteban** [comment] 2017-11-10 23:26
Duplicate of #821

**Comment by oesteban** [comment] 2017-11-10 23:27
Let's follow up conversation there.

**Closed by oesteban** 2017-11-10 23:27 UTC
