### ISSUE TITLE
MemoryError in signal extraction

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#886] opened 2017-12-12 15:09 UTC
```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.0', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 259, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 581, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 163, in run
    result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 222, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 62, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 404, in run
    self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 639, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 485, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/nilearn.py", line 83, in _run_interface
    signals.append(masker.fit_transform(self.inputs.in_file))
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/input_data/nifti_maps_masker.py", line 213, in fit_transform
    return self.fit().transform(imgs, confounds=confounds)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/input_data/nifti_maps_masker.py", line 319, in transform_single_imgs
    verbose=self.verbose)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py", line 283, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/input_data/base_masker.py", line 98, in filter_and_extract
    memory_level=memory_level)(imgs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py", line 283, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/input_data/nifti_maps_masker.py", line 29, in __call__
    mask_img=self._resampled_mask_img_)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nilearn/regions/signal_extraction.py", line 270, in img_to_signals_maps
    data[maps_mask, :])[0].T
  File "/usr/local/miniconda/lib/python3.6/site-packages/scipy/linalg/basic.py", line 909, in lstsq
    resids = np.sum(np.abs(x[n:])**2, axis=0)
MemoryError
```
https://openneuro.org/datasets/ds001181/versions/00001?app=FMRIPREP&version=44&job=5a2ecd2efce2fd0001047fd0

Could be related to #657

**Comment by effigies** [comment] 2017-12-12 15:24
What's the shape of the BOLD series, and are you using `--low-mem`? Also, we're using `SignalExtraction` to take a mean time series across a set of voxels defined by a mask, right? Just looking at the traceback, which involves a least squares regression, I wonder if we can write a simpler and less memory-intensive interface to do this.

**Comment by chrisfilo** [comment] 2017-12-12 15:31
I'm trying again with `--low-mem`. On poor wi-fi at the moment, but you should have access to this dataset on openneuro.

**Comment by effigies** [comment] 2017-12-12 15:35
I don't.

**Comment by chrisfilo** [comment] 2017-12-12 15:39
Could you try to log out and back in again (using your gmail account)?

**Comment by effigies** [comment] 2017-12-12 15:40
Got it. Thanks.

**Comment by chrisfilo** [comment] 2017-12-12 22:46
With `--low-mem` I get

```
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 62, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 404, in run
    self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 639, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 485, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/images.py", line 460, in _run_interface
    img.to_filename(out_fname)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/filebasedimages.py", line 334, in to_filename
    self.to_file_map()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/analyze.py", line 1053, in to_file_map
    data = self.get_data()
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/dataobj_images.py", line 202, in get_data
    data = np.asanyarray(self._dataobj)
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 291, in __array__
    return apply_read_scaling(raw_data, self._slope, self._inter)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/volumeutils.py", line 967, in apply_read_scaling
    arr = arr + inter
MemoryError
```

**Comment by chrisfilo** [comment] 2017-12-13 04:22
I also run it with low-mem, but without force-syn options and I got memory error in linalg (as for the first time). https://openneuro.org/datasets/ds001181/versions/00001?app=FMRIPREP&version=45&job=750adbe7-9910-4272-b758-69da4180f6cb

**Comment by effigies** [comment] 2017-12-14 15:38
That next-to-last error (https://github.com/poldracklab/fmriprep/issues/886#issuecomment-351220684) is in `ValidateImage`. Given we might be writing out the image, we should annotate those nodes with an appropriately large `mem_gb`.

And it seems clear we're under-estimating the size of the `SignalExtraction` (or possibly other things that are running at the same time). But I really think this should be doable in the size of a single load of the image + a mask, unless I misunderstand what's being done.

**Comment by oesteban** [comment] 2017-12-14 15:52
The "good" news is that we are not getting those many allocation errors anymore :P

**Comment by oesteban** [comment] 2018-04-30 18:26
Still dying due to memory allocation, at least without `--low-mem`
```
180428-17:58:18,865 workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_M80375143_wf.func_preproc_ses_1_task_rest_run_01_wf.bold_confounds_wf.rois_plot" in "/root/src/fmriprep/work/fmriprep_wf/single_subject_M80375143_wf/func_preproc_ses_1_task_rest_run_01_wf/bold_confounds_wf/rois_plot".
180428-17:58:18,871 workflow INFO:
	 [Node] Running "rois_plot" ("niworkflows.interfaces.masks.ROIsPlot")
180428-17:58:54,210 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_M80375143_wf.func_preproc_ses_1_task_rest_run_01_wf.bold_confounds_wf.rois_plot" (/root/src/fmriprep/work/fmriprep_wf/single_subject_M80375143_wf/func_preproc_ses_1_task_rest_run_01_wf/bold_confounds_wf/rois_plot)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.11', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 274, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 602, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 168, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 571, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/masks.py", line 268, in _run_interface
    compress=self.inputs.compress_report
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 266, in plot_segs
    **plot_params)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 309, in _plot_anat_with_contours
    svg = extract_svg(display, compress=compress)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 181, in extract_svg
    image_svg = svg_compress(image_svg, compress)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/viz/utils.py", line 144, in svg_compress
    stdout=subprocess.PIPE, check=True, close_fds=True).stdout
  File "/usr/local/miniconda/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/miniconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/miniconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

Running 1.0.11 with `--low-mem`.

**Comment by oesteban** [comment] 2018-05-01 20:59
Seems to work fine with `--low-mem`.

https://openneuro.org/datasets/ds001181/versions/00001?app=FMRIPREP&version=57&job=5914cccc-10a4-4473-9ee4-d769be3b35f8

Should we close this one?

**Comment by effigies** [comment] 2018-05-01 21:02
Sounds good to me.

**Comment by oesteban** [comment] 2018-05-04 00:55
@chrisfilo I will clean up this one, please reopen if you'd like to investigate this further.

**Closed by oesteban** 2018-05-04 00:55 UTC
Labels: bug, memory
