### ISSUE TITLE
Installation from a fresh virtualenv doesn't install numpy

### ISSUE THREAD

**Issue by glatard** [poldracklab/fmriprep#1430] opened 2018-12-03 19:33 UTC
Using Python 3.6.6 in a fresh virtualenv:
```
$ pip install . 
Processing /home/glatard/code/fmriprep
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-60bzras8/setup.py", line 101, in <module>
        main()
      File "/tmp/pip-req-build-60bzras8/setup.py", line 15, in main
        from numpy import get_include
    ModuleNotFoundError: No module named 'numpy'
```
Sorry for not fixing this, I've tried to add `numpy` to various places where dependencies seems to be listed but couldn't find the right one yet.

**Comment by oesteban** [comment] 2018-12-03 21:09
The issue is that numpy is a setup require (https://github.com/poldracklab/fmriprep/blob/master/setup.py#L82).

I think that unfortunately, setuptools cannot install them ahead of time (it is a chicken and egg problem: setup.py imports numpy before it fetches the dependencies).

The only way of overcoming this is improving documentation. Alternatively, adding it to the requirements.txt and asking people to pip install -r requirements.txt would work out (although defeats the purpose of requirements.txt to be a dev tool).

Maybe we are misinterpreting how setuptools work, happy to take any actions to improve this.

**Comment by oesteban** [comment] 2019-01-12 19:35
Hi @glatard, do you think my reply addressed the issue? Although I couldn't give you any solution on fMRIPrep's side, do you think we can close this one?

**Comment by glatard** [comment] 2019-01-13 01:08
yes, I guess you can close it, thanks!

**Closed** 2019-01-13 13:20 UTC
