### ISSUE TITLE
Error with N4BiasFieldCorrection

### ISSUE THREAD

**Issue by IanEisenberg** [poldracklab/fmriprep#1579] opened 2019-04-10 16:56 UTC
Silent error with N4BiasFieldCorrection. I reran with the "verbose" flag and found that the input images do not occupy the same physical space. Same  as #1463, but potentially still a problem for sbref files. Besides fixing the error, I suggest adding the verbose flag to the N4BiasFieldCorrection command.

```
singularity exec poldracklab_fmriprep_1.3.1-2019-03-06-9db26dbbab52.simg N4BiasFieldCorrection -d 3 --input-image /scratch/users/ieisenbe/fmriprep_wf/single_subject_s130_wf/func_preproc_ses_1_task_motorSelectiveStop_run_1_wf/bold_reference_wf/validate_ref/sub-s130_ses-1_task-motorSelectiveStop_run-1_sbref_valid.nii.gz --mask-image /scratch/users/ieisenbe/fmriprep_wf/single_subject_s130_wf/func_preproc_ses_1_task_motorSelectiveStop_run_1_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/check_hdr/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask_trans_dil_hdr.nii.gz --output sub-s130_ses-1_task-motorSelectiveStop_run-1_sbref_valid_corrected.nii.gz -v
```
```
Running N4 for 3-dimensional images.

Exception caught: 
itk::ExceptionObject (0x203c6e0)
Location: "unknown" 
File: /tmp/ANTs/build/ITKv4-install/include/ITK-4.11/itkImageToImageFilter.hxx
Line: 250
Description: itk::ERROR: N4BiasFieldCorrectionImageFilter(0x202c780): Inputs do not occupy the same physical space! 
InputImage Origin: [-1.0183700e+02, -1.1194000e+02, -3.2479801e+01], InputImage_1 Origin: [-1.0183700e+02, -1.1163189e+02, -3.2819803e+01]
        Tolerance: 8.8000002e-06
InputImage Direction: 1.0000000e+00 0.0000000e+00 0.0000000e+00
0.0000000e+00 1.0000000e+00 0.0000000e+00
0.0000000e+00 0.0000000e+00 1.0000000e+00
, InputImage_1 Direction: 1.0000000e+00 0.0000000e+00 0.0000000e+00
0.0000000e+00 9.9516690e-01 9.8197960e-02
0.0000000e+00 -9.8197958e-02 9.9516690e-01

        Tolerance: 1.0000000e-06
```

**Comment by oesteban** [comment] 2019-04-10 18:41
Note to self: enable the `verbose` flag for `N4BiasFieldCorrection` in all instances.

Possible related: https://neurostars.org/t/fmriprep-n4biasfieldcorrection-fails/4043

**Comment by oesteban** [comment] 2019-04-11 00:12
This looks indeed a duplicate of #1463. Thanks for the research @IanEisenberg 

```
$ nib-ls *_sbref.nii.gz
sub-s130_ses-1_task-motorSelectiveStop_run-1_sbref.nii.gz float64 [100, 100,  64,   4] 2.20x2.20x2.20x6.00   sform
sub-s130_ses-1_task-rest_run-1_sbref.nii.gz               float64 [100, 100,  64,   4] 2.20x2.20x2.20x6.00   sform
```

There are 4 volumes on the 4th dimension.

**Closed** 2019-04-11 06:46 UTC
Labels: bug, effort: medium, impact: high, skullstripping
