### ISSUE TITLE
Update docs for freesurfer as a strict requirement

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#893] opened 2017-12-18 16:10 UTC
I opened #892 due to confusion about the requirement of a Freesurfer license to run `fmriprep`, as discussed in #880. 

Is the current preference to make Freesurfer a strict requirement, and update associated documentation? Particularly the [usage notes](http://fmriprep.readthedocs.io/en/latest/usage.html), [installation guide](http://fmriprep.readthedocs.io/en/latest/installation.html) and `--no-freesurfer` option. Alternatively, should Freesurfer remain a requirement for only some options, in which case we would implement a series of checks in `run.py`?

Personally I'd lean towards the checks, but I understand concerns that they could grow over time.

**Comment by oesteban** [comment] 2017-12-18 19:26
Hi @emdupre, in the latest version of FMRIPREP we made FreeSurfer a mandatory dependency. The issue is that, even using the `--no-freesurfer` option, when more than one T1 are found then FreeSurfer is used regardless the option.

In that situation, we had the option of writing an alternative workflow for merging the T1s (without FS) or making FS mandatory. We took the easy way and turned the `--no-freesurfer` option into `--no-reconall` to better reflect what is exactly being disabled.

We probably should move that into the `--disable` option, but for now, it is mandatory.

However, nothing of this is final: considering your opinion we will try to identify the situation where we don't want to use FS but we find several T1s (and raise error in that case). In the mean time, I agree the documentation is currently very unclear regarding this.

**Comment by emdupre** [comment] 2017-12-18 20:03
I'm happy to update the documentation, if that's the preferred path forward ! I just think the present situation creates unnecessary confusion (at least it did for me :)

**Comment by oesteban** [comment] 2017-12-18 20:27
I totally agree, right now it is very confusing. If you update the documentation it will be very very much appreciated!

**Comment by effigies** [comment] 2017-12-19 17:31
I agree that moving to `--ignore surface` or something like that would be good. I'll review #894.

**Closed** 2017-12-20 15:20 UTC
Labels: documentation, freesurfer, UX
