### ISSUE TITLE
normalizing/conforming input data

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#260] opened 2016-12-09 19:25 UTC
To make sure data fed to FMRIPREP from different datasets is looking as similar as possible we are currently reorienting anatomical images to RAS. However, there is more that can be done:
- make sure that the information in the header concerning data type and affine transformation (sform, qform) are correct; fix if possible
- apply the same procedure to all input data (_bold, _sbref, fieldmaps etc.)

Problems:
- If we change the orientation of input files we need to adjust the phase encoding direction as well.
- Applying those fixes to big 4D _bold files will create an (almost) identical copy and waste a lot of disk space

**Comment by oesteban** [comment] 2017-07-17 21:00
Possible duplicate of #581, #388, #433 ?

**Comment by effigies** [comment] 2017-07-18 17:31
Copying in part of https://github.com/poldracklab/fmriprep/issues/573#issuecomment-313799752:

> To address further issues raised in #260:
> 
> * If we change the orientation of input files we need to adjust the phase encoding direction as well.
> 
> NIfTI does have a phase_dim header entry. We could update the header, and use that later.
> 
> * Applying those fixes to big 4D _bold files will create an (almost) identical copy and waste a lot of disk space
>
> True, and adding the PE direction header entry will cause the same issue, if we don't already need to create a new file.
> 
> I haven't tried this out yet, but we could consider creating a filename.hdr.gz with a data offset matching the original header, and symlink to the original file with filename.img.gz. Assuming this works, we couldn't reorient, but we could update the headers without copying the data.

**Comment by oesteban** [comment] 2017-10-11 18:03
Superseded by new issue (link above)

**Closed by oesteban** 2017-10-11 18:03 UTC
