### ISSUE TITLE
OSError: Error occurred while trying to decode JSON from file 

### ISSUE THREAD

**Issue by alicebizeul** [poldracklab/fmriprep#2194] opened 2020-06-19 16:42 UTC
Hi, 

I am trying to run fmriprep on a Datalad dataset (Openneuro ds000224, which uses the BIDS format) using the fmriprep-20.1.1.simg Singularity image. I am using the following command line: 

`unset PYTHONPATH CONDA_PYTHON_EXE; singularity run --cleanenv /om/user/abizeul/my_images/fmriprep-20.1.1.simg /om/user/abizeul/my_images/ds000224 /om/user/abizeul/my_images/fmri_prep participant --task-id rest --participant-label sub-MSC01 --ignore fieldmaps slicetiming sbref --skull-strip-t1w 'skip' --output-spaces MNI152NLin6Asym --fs-no-reconall --work-dir /om/user/abizeul/my_images/work/` 

And am getting the following error which I struggle to understand (I don't see any JSON file in my dataset folder): 

```
WARNING: seccomp requested but not enabled, seccomp library is missing or too old
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 226, in index_metadata
    payload = json.load(handle)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 5 (char 214)

The above exception was the direct cause of the following exception:
```

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 568, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 548, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 186, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 396, in init
    "derivatives", re.compile(r'^\.')))
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 262, in __init__
    indexer.index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 230, in index_metadata
    raise IOError(msg) from e
OSError: Error occurred while trying to decode JSON from file '/om/user/abizeul/my_images/ds000224/.git/annex/objects/8M/J1/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json'.
```

Thank you in advance for the help !

**Comment by bpinsard** [comment] 2020-06-19 17:42
It seems that the problem is in the json files of the dataset, for instance: 
`https://github.com/OpenNeuroDatasets/ds000224/blob/master/sourcedata/phenotype/KBIT2.json`
the quotes used are not valid for json.
Though in your case, the file is not in git, but in git-annex, so it might be a different file/folder.

**Comment by oesteban** [comment] 2020-06-19 21:00
@bpinsard is right - it seems pybids is indexing under `.git/`. @effigies, do you think there's a problem with the way we initialize the BIDSLayout?

https://github.com/poldracklab/fmriprep/blob/e5c083039d5390778071f6800deb1142860a4db5/fmriprep/config.py#L406-L411

The regular expression should match `.git/` correct?

**Comment by effigies** [comment] 2020-06-19 21:11
Yes. It's not clear that's the issue, though. It may be resolving the symlink for some reason.

**Comment by oesteban** [comment] 2020-06-19 21:13
Maybe some JSON files are on S3 and were not added `--to-git`.

**Comment by effigies** [comment] 2020-06-19 21:38
I'm not really sure how this is happening. I can't find `MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json` in any version of the dataset that's on OpenNeuro.

@alicebizeul Could you show the output for the following (copy-paste the whole thing, including parentheses):

```Shell
(
    set -x
    DATASET=/om/user/abizeul/my_images/ds000224
    git -C dataset show-ref
    tree $DATASET | grep MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
    cat $DATASET/.git/annex/objects/8M/J1/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
)
```

**Comment by alicebizeul** [comment] 2020-06-20 17:55
Thank you for your answers ! 
Indeed, some .json files in the .git/annex folder had typos. 

Here is the output of the command @effigies : 

`+DATASET=/om/user/abizeul/my_images/ds000224
+git -C dataset show-ref
fatal: Cannot change to 'dataset': Aucun fichier ou dossier de ce type
+tree /om/user/abizeul/my_images/ds000224
+grep --color=auto MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
│       ├── BAS_BIS.json -> ../../.git/annex/objects/8M/J1/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
+cat /om/user/abizeul/my_images/ds000224/.git/annex/objects/8M/J1/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
{
    "MeasurementToolMetadata": {
        "Description": "Behavioral Approach System / Behavioral Inhibition System scales",
        "TermURL": "http://www.cognitiveatlas.org/term/id/trm_56a9137d9dce1"
    },
    "BAS_drive": {
        "Description": "Persistent pursuit of goals",
        "Units": "summed Likert scores"
    },
    "BAS_fun_seeking": {
        "Description": "Desire for new rewards",
        "Units": "summed Likert scores"
    },
    "BAS_reward_responsiveness": {
        "Description": "Positive response to reward",
        "Units": "summed Likert scores"
    },
    "BIS": {
        "Description": "Sensitivity to negative events / anxiety",
        "Units": "summed Likert scores"
    }
}`

**Comment by effigies** [comment] 2020-06-20 17:56
Sorry, that should have been `git -C $DATASET`.

**Comment by alicebizeul** [comment] 2020-06-20 17:58
@effigies 

```
+ DATASET=/om/user/abizeul/my_images/ds000224
+ git -C dataset show-ref
fatal: Cannot change to 'dataset': Aucun fichier ou dossier de ce type
+ tree /om/user/abizeul/my_images/ds000224
+ grep --color=auto MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
│       ├── BAS_BIS.json -> ../../.git/annex/objects/8M/J1/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
+ cat /om/user/abizeul/my_images/ds000224/.git/annex/objects/8M/J1/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
{
    "MeasurementToolMetadata": {
        "Description": "Behavioral Approach System / Behavioral Inhibition System scales",
        "TermURL": "http://www.cognitiveatlas.org/term/id/trm_56a9137d9dce1"
    },
    "BAS_drive": {
        "Description": "Persistent pursuit of goals",
        "Units": "summed Likert scores"
    },
    "BAS_fun_seeking": {
        "Description": "Desire for new rewards",
        "Units": "summed Likert scores"
    },
    "BAS_reward_responsiveness": {
        "Description": "Positive response to reward",
        "Units": "summed Likert scores"
    },
    "BIS": {
        "Description": "Sensitivity to negative events / anxiety",
        "Units": "summed Likert scores"
    }
}
```

**Comment by alicebizeul** [comment] 2020-06-20 17:59
@effigies 

```
+ DATASET=/om/user/abizeul/my_images/ds000224
+ git -C /om/user/abizeul/my_images/ds000224 show-ref
463feeb1e85dc426c87157bf28c1433dc54663ee refs/heads/git-annex
4f23095f5e78e1213289069811973fc0e119337e refs/heads/master
4f23095f5e78e1213289069811973fc0e119337e refs/remotes/origin/HEAD
f4909df08e7d79aca209cb2552c0823c14d1a2c5 refs/remotes/origin/git-annex
86e1318ab32ef8ed1b2727503f65706cfda88939 refs/remotes/origin/incoming
7ab1e9f70694c5fa69c5dc2f7a0611f7787c1e2a refs/remotes/origin/incoming-processed
83a15e4358622d0771aa9a498e0cdb38510a2681 refs/remotes/origin/incoming-s3-openneuro
4f23095f5e78e1213289069811973fc0e119337e refs/remotes/origin/master
4f23095f5e78e1213289069811973fc0e119337e refs/remotes/origin/synced/master
af4c9eb5fb44b05f1eceeea760d4a769647825dd refs/tags/1.0.0
9f974d625661dd27b7c81c1614490ab6fda5b008 refs/tags/1.0.1
70737a78d40bd96cd9326644ac60559172ceff4a refs/tags/1.0.2
d8b88af216136b1cd885ed7def9fffaab2cc8c86 refs/tags/1.0.2+1
+ tree /om/user/abizeul/my_images/ds000224
+ grep --color=auto MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
│       ├── BAS_BIS.json -> ../../.git/annex/objects/8M/J1/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
+ cat /om/user/abizeul/my_images/ds000224/.git/annex/objects/8M/J1/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json/MD5E-s762--34d60e77b84ea40b5df9ce3e914a5400.json
{
    "MeasurementToolMetadata": {
        "Description": "Behavioral Approach System / Behavioral Inhibition System scales",
        "TermURL": "http://www.cognitiveatlas.org/term/id/trm_56a9137d9dce1"
    },
    "BAS_drive": {
        "Description": "Persistent pursuit of goals",
        "Units": "summed Likert scores"
    },
    "BAS_fun_seeking": {
        "Description": "Desire for new rewards",
        "Units": "summed Likert scores"
    },
    "BAS_reward_responsiveness": {
        "Description": "Positive response to reward",
        "Units": "summed Likert scores"
    },
    "BIS": {
        "Description": "Sensitivity to negative events / anxiety",
        "Units": "summed Likert scores"
    }
}
```

**Comment by oesteban** [comment] 2020-08-09 07:53
Should we just pin a later release of pybids?

**Comment by effigies** [comment] 2020-08-09 11:20
It's not pybids, but the data containing invalid characters.

**Comment by oesteban** [comment] 2020-08-09 12:48
Then I guess this can be closed, right?

**Closed** 2020-08-09 12:54 UTC
Labels: bug
