### ISSUE TITLE
Problems during processing with 1.5.0

### ISSUE THREAD

**Issue by JoffJones** [poldracklab/fmriprep#1798] opened 2019-09-27 16:25 UTC
Hi there,

I am trying to re-run some preprocessing using the 1.5.0 stable release but encountered an error only when using the -use-aroma flag. Any help would be appreciated! 

FYI this is run using singularity on a HPC. 

The error reported in the html report is: 
```
Node Name: _autorecon31
```

The command with: 
```
/usr/local/miniconda/bin/fmriprep /CALM_BIDS_New_2 /CALM_BIDS_New_2/derivatives/fmriprep-1.5.0-test-aroma participant --participant_label 004 -v -w /CALM_BIDS_New_2/derivatives/fmriprepwork-1.5.0-test-aroma --skull-strip-template MNIPediatricAsym:cohort-1 --output-spaces MNIPediatricAsym:cohort-1:res-2 T1w MNI152NLin6Asym:res-2 MNI152NLin2009cAsym fsaverage --use-aroma --fs-license-file /CALM/license.txt --write-graph --fd-spike-threshold 0.5 --dvars-spike-threshold 0.5 --notrack --resource-monitor
```
The output with:
[use-aroma.txt](https://github.com/poldracklab/fmriprep/files/3663700/use-aroma.txt)

The command without:
```
/usr/local/miniconda/bin/fmriprep /CALM_BIDS_New_2 /CALM_BIDS_New_2/derivatives/fmriprep-1.5.0-test participant --participant_label 001 -v -w /CALM_BIDS_New_2/derivatives/fmriprepwork-1.5.0-test --skull-strip-template MNIPediatricAsym:cohort-1 --output-spaces MNIPediatricAsym:cohort-1:res-2 T1w MNI152NLin6Asym:res-2 MNI152NLin2009cAsym fsaverage --fs-license-file /CALM/license.txt --write-graph --fd-spike-threshold 0.5 --dvars-spike-threshold 0.5 --notrack --resource-monitor 
```
The output without:
[no-aroma.txt](https://github.com/poldracklab/fmriprep/files/3663708/no-aroma.txt)

**Comment by oesteban** [comment] 2019-09-30 19:03
Hi @JoffJones please note that these are two different participants. Looking at your logs, participant 004 (with `--use-aroma`) crashed during FreeSurfer operation. You might want to try it again or make sure you use an existing FreeSurfer folder.

Regarding participant 001 (without `--use-aroma`), it indeed contains an error that is likely to go away if you do not reuse the work directory anymore.

Please note that neither problem is related to ``--use-aroma``.

**Comment by JoffJones** [comment] 2019-10-03 09:43
Hi @oesteban, 

To follow up, I ran 3 subjects seemingly successfully with --use-aroma and subject 004 without the flag and I'm currently running 004 again with --use-aroma. However, the logs indicate some potential errors, some of these you picked up on in the log file of 001 (no-aroma.txt) but most are inconsistent across subjects. I've briefly summarised the errors below and which log files they occur in. Please can you let me know if you think it would be problematic to use the outputs? So far they look OK.

> FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use 
> arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, arr[np.array(seq)]`, which will result either in an error or a different result.
> pandoc-citeproc: reference mnipediatricasym not found
**Occurs in all outputs.**

> 191002-09:52:10,388 nipype.utils ERROR:
> 	 No metadata was found in the pkl file. Make sure you are currently using the same Nipype version from the generated pkl.
> 191002-09:52:10,391 nipype.workflow WARNING:
> 	 Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:
> 	Node: fmriprep_wf.single_subject_002_wf.anat_preproc_wf.brain_extraction_wf.atropos_wf.09_relabel_wm
> 	Interface: nipype.interfaces.ants.utils.MultiplyImages

> AttributeError: 'NoneType' object has no attribute 'outputs'
**Occurs in 'aroma-sub-002',** 


> 191002-15:15:18,589 nipype.utils ERROR:
> 	 No metadata was found in the pkl file. Make sure you are currently using the same Nipype version from the generated pkl.
> 191002-15:15:18,589 nipype.workflow WARNING:
> 	 Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:
> 
> 	Node: fmriprep_wf.single_subject_003_wf.func_preproc_task_rest_wf.bold_std_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.check_hdr
> 	Interface: niworkflows.interfaces.images.MatchHeader

> AttributeError: 'NoneType' object has no attribute 'outputs'
**Occurs in 'aroma-sub-003'**

> 191002-17:13:51,476 nipype.utils ERROR:
> 	 No metadata was found in the pkl file. Make sure you are currently using the same Nipype version from the generated pkl.
> 191002-17:13:51,480 nipype.workflow WARNING:
> 	 Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:
> 
> 	Node: fmriprep_wf.single_subject_004_wf.func_preproc_task_rest_wf.bold_std_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.pre_mask_dilate
> 	Interface: nipype.interfaces.fsl.maths.DilateImage

> AttributeError: 'NoneType' object has no attribute 'outputs'
**Occurs in 's4-noaroma-sub-004'**


> 191002-16:34:41,89 nipype.workflow WARNING:
> 	 Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:
> FileNotFoundError: [Errno 2] No such file or directory: 'result_gen_ref.pklz'
**Occurs in 'aroma-sub-002', 'aroma-sub-003'**

**Comment by oesteban** [comment] 2019-10-03 20:58
> Occurs in all outputs.
> ```
> FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use
> arr[tuple(seq)]instead ofarr[seq]. In the future this will be interpreted as an array index, arr[np.array(seq)], which will result either in an error or a different result.
> pandoc-citeproc: reference mnipediatricasym not found
> ```

First two lines are a `FutureWarning` probably arising from Nipype - nothing to worry about for now as a user. The third line is a problem with TemplateFlow - at the moment all template citations are kept statically on a `.bib` file in the repo. We need to implement some sort of automated procedure to extract them from TemplateFlow directly.

The next two are two open issues in Nipype which are under investigation (nipy/nipype#3009 and nipy/nipype#3014):
```
AttributeError: 'NoneType' object has no attribute 'outputs'
```
and
```
FileNotFoundError: [Errno 2] No such file or directory: 'result_gen_ref.pklz'
```

In principle, these are pretty annoying but should not break your execution. Please check the integrity of results derived from these participants.

The remainder of this issue is about ICA-AROMA, and it is a duplicate of https://neurostars.org/t/ica-aroma-fmriprep-using-child-template/5139 - let's follow up there.

Closing this one - please reopen if I did not address all the concerns (except for AROMA).

**Closed by oesteban** 2019-10-03 20:58 UTC
Labels: bug
