### ISSUE TITLE
ROIs in BOLD space - weird contours in last slice

### ISSUE THREAD

**Issue by SRSteinkamp** [poldracklab/fmriprep#1171] opened 2018-06-18 09:36 UTC
Dear all, 

I've been using fmriprep 1.0.2 in the past an decided to rerun the preprocessing using fmriprep 1.1.1. 

I noticed that in almost all reportlets in the newer version there are weird structures in the last slide of the Rois in BOLD space: 

![fmriprep_102.pdf](https://github.com/poldracklab/fmriprep/files/2110659/fmriprep_102.pdf)
![fmriprep111.pdf](https://github.com/poldracklab/fmriprep/files/2110660/fmriprep111.pdf)

I looked into the masks etc. and except that the fmriprep 1.0.2 masks are not as smooth as the 1.1.1 masks there doesn't seem to be a difference between the images. 

The command I've been running:
``
docker run -it --rm -v path/data/BIDS/:/data -v path/data/BIDS/derivatives/fmriprep_1_1_1/:/out -v path/data/BIDS/derivatives/W:/scrap -v path/data/BIDS/derivatives/.license:/license poldracklab/fmriprep:1.1.1 /data /out participant -w /scrap --fs-license /license --mem_mb 25000 --fs-no-reconall --no-submm-recon --verbose --use-syn-sdc --notrack --resource-monitor --nthreads 12 --participant-label xxx1 xxx2 xxx3
``

I'd be glad if you could give me a hint, where in which mask file these issues could appear, or in the best case that it is just a visual issue and can be ignored, so that I don't have to rerun the whole thing again...

Apart from the ROI images, everything in the reportlets seems to be fine and working as expected. 

Best,
Simon

**Comment by chrisfilo** [comment] 2018-06-18 09:38
I think this might be a duplicate of https://github.com/poldracklab/fmriprep/issues/1152 - could you confirm? (the images did not seem to upload correctly)

**Comment by SRSteinkamp** [comment] 2018-06-18 09:45
Yes it's a duplicate, sorry I seem to have missed #1152 while searching the open issues.

**Comment by chrisfilo** [comment] 2018-06-18 09:56
No worries! Let's move the conversation there.

**Closed by chrisfilo** 2018-06-18 09:56 UTC
