### ISSUE TITLE
Show errors for missing images in reports.

### ISSUE THREAD

**Issue by rwblair** [poldracklab/fmriprep#66] opened 2016-06-07 22:17 UTC
If an image fails to generate report should put in additional information about failures from image generation workflows.

**Comment by oesteban** [comment] 2016-12-08 16:47
I think this is currently well covered with the new reports.

**Comment by oesteban** [comment] 2016-12-15 21:58
Yep, the problem is that the out_report output trait is never populated: the node fails and, even though a reportlet is generated, the nipype engine will not consider it.

**Comment by chrisfilo** [comment] 2017-01-05 18:39
The reports should include the content of all generated crashfiles. Here's the code for reading crashfiles: https://github.com/nipy/nipype/blob/master/nipype/scripts/crash_files.py (could be easily adapted with mocking `print`).

We briefly discussed adding optional plain text crashfiles to nipype (see https://github.com/nipy/nipype/issues/1184), but I doubt this can happen before the next nipype release (rc1 was just released).

**Comment by rwblair** [comment] 2017-01-05 19:24
In niworkflows for the definition of ReportCapableInterface there is check to see if the interface ran successfully and if not to call _generate_error_report: https://github.com/poldracklab/niworkflows/blob/master/niworkflows/common/report.py#L59

I'm looking into writing the crash information out to the reportlet here. That being said in the reports that we have on afterhours I'm not seeing any instances of the html from _generate_error_report.

**Comment by chrisfilo** [comment] 2017-01-05 19:45
I would suggest a different approach. After running the workflow that exits with errors 
- crawl the crashfile directory and identify all crashfiles belonging to each subject analyzed in this run (you might need additional daytime restrictions to avoid capturing crashfiles from historical runs)
- append error information to corresponding subject specific HTML reports report

This way we will be able to capture all errors (not only those coming from Report Capable interfaces). It will also avoid having to deal with the problematic case of a failed node that populates error reportlet that should be send to a datasink (what @oesteban mentioned in https://github.com/poldracklab/fmriprep/issues/66#issuecomment-267456545).

**Comment by chrisfilo** [comment] 2017-01-11 17:30
Closed by #298

**Closed by chrisfilo** 2017-01-11 17:30 UTC
Labels: error reporting, reports
