### ISSUE TITLE
ds000233 coregistration issues

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#735] opened 2017-10-02 18:26 UTC
A bit more minor than others, but could be significant nonetheless
![image](https://user-images.githubusercontent.com/238759/31092806-68a403f0-a764-11e7-8476-79213987f5c2.png)

sub-rid000024_task-beh_run-1

**Comment by effigies** [comment] 2017-10-10 20:30
This looks (from the image) like it may be being caused by excessive motion in the  images averaged to construct the reference. I'll have a look at the BOLD series and see if this is a correct assessment, and if there's any way we can produce a cleaner reference image.

**Comment by effigies** [comment] 2017-10-11 15:34
I think it's just a low-contrast image, after all. I didn't see any evidence of motion artifacts in the series as a whole, or the specific volumes averaged (21-40).

**Comment by oesteban** [comment] 2017-10-11 16:14
Since this is an issue derived from the poor quality of data, I'll remove it from Phase I and assign it to future with the hopes of coming back with fresh ideas at some point in time.

**Comment by oesteban** [comment] 2017-10-12 21:49
I'm checking back on this. I've run this subject without SDC and it seems to me that this is an artifact of susceptibility distortion.

I also got to understand the crazy contrast of this image. The problem is that the original snapshot is done on the flickering panel, at a point in time where some of the underlying T1 is already seen as the fusion is already started. The contrast of the reference image is OK if you look at it in a proper viewer.

I've created this wiki: https://github.com/poldracklab/fmriprep/wiki/SDC-SyN:-very-hard-cases to keep track of these cases and use the data collected to improve our SDC techniques.

Closing this issue, since co-registration looks good except for distorted areas.

**Closed by oesteban** 2017-10-12 21:49 UTC
Labels: bug
