### ISSUE TITLE
Consider "EPImean": using the mean across all tasks/runs to do EPI -> T1 coregistrations

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#253] opened 2016-12-08 07:40 UTC
This would help with cases such as rewardBeast sub-317 where half of the runs have bad distortion and signal dropout, but the other half are fine. Such cases are rare though.

**Comment by effigies** [comment] 2017-07-18 17:28
Does this still seem like a good idea, and, just to be clear, the mechanics of this would be to move to an (EPI -> mean EPI) FLIRT alignment + (mean EPI -> T1w)?

**Comment by chrisfilo** [comment] 2017-07-18 17:32
Correct.

**Comment by effigies** [comment] 2017-07-28 18:03
Thinking about what's involved in this:

- Single workflow that takes all BOLD series
- Each series needs to be SDC unwarped
- Resulting reference files then merged with `StructuralReference`, and (EPI -> mean EPI) transform saved
- Mean EPI aligned to T1w image

This will involve a fairly major refactor from the current, isolated processing of each BOLD series. One problem with this approach is that you can get different results based on whether your analyze all tasks or just a subset in the same process.

However, if we took an EPInorm approach, then there's a common space to which all EPIs are registered that doesn't depend on which subset of tasks have been specified.

WDYT?

**Comment by oesteban** [comment] 2017-07-28 18:22
+1 to EPInorm approach. And we have the paper to support the decision.

I would leave that for the future though, beyond 1.0.0.

**Comment by effigies** [comment] 2017-07-28 18:29
Opened an issue for EPInorm, if that's the route we decide to go.

**Comment by chrisfilo** [comment] 2017-07-28 23:59
@oscar - from what I know EPInorm has not been compared with syn based SDC. It actually might not provide any improvement.

@effigies indeed this would be the case, but I don't think it's a big issue

**Comment by oesteban** [comment] 2017-11-10 23:58
Duplicate of #450 - I'll copy one of @effigies' comments there because it is relevant.

**Closed by oesteban** 2017-11-10 23:58 UTC
