### ISSUE TITLE
KeyError: 'RepetitionTime' after version 1.0.12

### ISSUE THREAD

**Issue by steanze** [poldracklab/fmriprep#1155] opened 2018-06-01 19:07 UTC
I am running fmriprep executing the docker container with singularity. Version 1.0.12 and later produce the following error: KeyError: 'RepetitionTime'
The key 'RepetitionTime' is present in the .json file, and version 1.0.11 and 1.0.10 do not produce this error.

**Comment by effigies** [comment] 2018-06-01 19:08
Hi, thanks for the report. Can you provide the full traceback?

**Comment by steanze** [comment] 2018-06-01 19:10
Thanks for the quick reply! Here is the full traceback:
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 510, in build_workflow
    ignore_aroma_err=opts.ignore_aroma_denoising_errors,
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 202, in init_fmriprep_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/base.py", line 458, in init_single_subject_wf
    ignore_aroma_err=ignore_aroma_err)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/bold/base.py", line 596, in init_func_preproc_wf
    name='carpetplot_wf')
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/workflows/bold/confounds.py", line 334, in init_carpetplot_wf
    tr=metadata['RepetitionTime'],
KeyError: 'RepetitionTime'

**Comment by effigies** [comment] 2018-06-01 19:52
Hmm. Unfortunately this doesn't describe which BOLD file produced the issue. Can you try:

```Shell
find $BIDS_DIR -name '*_bold.*'
find $BIDS_DIR -name '*_bold.json' -exec grep RepetitionTime "{}" +
```

Where `$BIDS_DIR` is the root of your BIDS directory?

**Comment by effigies** [comment] 2018-06-01 19:53
Also, have you [validated](https://incf.github.io/bids-validator/) your dataset?

**Comment by steanze** [comment] 2018-06-01 19:58
Hi! Yes, I have validated the dataset. It is the study forrest dataset. The issue is occurring for example with subject 16.

**Comment by steanze** [comment] 2018-06-01 20:00
Here is the output of find $BIDS_DIR -name '*_bold.*'

find  sub-01 -name '*_bold.*'
sub-01/func/sub-01_ses-localizer_task-movielocalizer_run-1_bold.json
sub-01/func/sub-01_ses-localizer_task-movielocalizer_run-1_bold.nii.gz
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-1_bold.json
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-1_bold.nii.gz
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-2_bold.json
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-2_bold.nii.gz
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-3_bold.json
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-3_bold.nii.gz
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-4_bold.json
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-4_bold.nii.gz
sub-01/func/sub-01_ses-localizer_task-retmapccw_run-1_bold.json
sub-01/func/sub-01_ses-localizer_task-retmapccw_run-1_bold.nii.gz
sub-01/func/sub-01_ses-localizer_task-retmapclw_run-1_bold.json
sub-01/func/sub-01_ses-localizer_task-retmapclw_run-1_bold.nii.gz
sub-01/func/sub-01_ses-localizer_task-retmapexp_run-1_bold.json
sub-01/func/sub-01_ses-localizer_task-retmapexp_run-1_bold.nii.gz
sub-01/func/sub-01_ses-localizer_task-retmapexpcon_run-1_bold.json
sub-01/func/sub-01_ses-localizer_task-retmapexpcon_run-1_bold.nii.gz
sub-01/func/sub-01_ses-movie_task-movie_run-1_bold.json
sub-01/func/sub-01_ses-movie_task-movie_run-1_bold.nii.gz
sub-01/func/sub-01_ses-movie_task-movie_run-2_bold.json
sub-01/func/sub-01_ses-movie_task-movie_run-2_bold.nii.gz
sub-01/func/sub-01_ses-movie_task-movie_run-3_bold.json
sub-01/func/sub-01_ses-movie_task-movie_run-3_bold.nii.gz
sub-01/func/sub-01_ses-movie_task-movie_run-4_bold.json
sub-01/func/sub-01_ses-movie_task-movie_run-4_bold.nii.gz
sub-01/func/sub-01_ses-movie_task-movie_run-5_bold.json
sub-01/func/sub-01_ses-movie_task-movie_run-5_bold.nii.gz
sub-01/func/sub-01_ses-movie_task-movie_run-6_bold.json
sub-01/func/sub-01_ses-movie_task-movie_run-6_bold.nii.gz
sub-01/func/sub-01_ses-movie_task-movie_run-7_bold.json
sub-01/func/sub-01_ses-movie_task-movie_run-7_bold.nii.gz
sub-01/func/sub-01_ses-movie_task-movie_run-8_bold.json
sub-01/func/sub-01_ses-movie_task-movie_run-8_bold.nii.gz

**Comment by steanze** [comment] 2018-06-01 20:00
Here is the second command:
find  sub-01 -name '*_bold.json' -exec grep RepetitionTime "{}" +
sub-01/func/sub-01_ses-localizer_task-movielocalizer_run-1_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-1_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-2_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-3_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-localizer_task-objectcategories_run-4_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-localizer_task-retmapccw_run-1_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-localizer_task-retmapclw_run-1_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-localizer_task-retmapexp_run-1_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-localizer_task-retmapexpcon_run-1_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-movie_task-movie_run-1_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-movie_task-movie_run-2_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-movie_task-movie_run-3_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-movie_task-movie_run-4_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-movie_task-movie_run-5_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-movie_task-movie_run-6_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-movie_task-movie_run-7_bold.json:            "RepetitionTime": 2000.00061035156, 
sub-01/func/sub-01_ses-movie_task-movie_run-8_bold.json:            "RepetitionTime": 2000.00061035156,

**Comment by effigies** [comment] 2018-06-01 20:03
If the issue is showing for subject 16, could you perform the above for `$BIDS_DIR/sub-16`?

**Comment by steanze** [comment] 2018-06-01 20:06
Yes, I updated my previous comment and it should show the results for subject 16 now.

**Comment by chrisfilo** [comment] 2018-06-01 20:09
are you sure this dataset validates without errors? It seems that `ses-<label>` folder level is missing

**Comment by steanze** [comment] 2018-06-05 20:50
Hi! I have modified the folder structure to match BIDS validation. I have fixed the "RepetitionTime" issue, now I am running into this error, that seems related to this issue: https://github.com/poldracklab/fmriprep/issues/843

Do you think this might also be related to slice timing? Thanks!

[Node] Setting-up "fmriprep_wf.single_subject_18_wf.func_preproc_ses_localizer_task_objectcategories_run_3_wf.bold_reference_wf.gen_ref" in "/mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_localizer_task_objectcategories_run_3_wf/bold_reference_wf/gen_ref".
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997:*+ WARNING:   If you are performing spatial transformations on an oblique dset, 
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997:  such as /mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_localizer_task_objectcategories_run_1_wf/bold_reference_wf/gen_ref/slice.nii.gz,
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997:  or viewing/combining it with volumes of differing obliquity,
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997:  you should consider running: 
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997:     3dWarp -deoblique 
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997:  on this and  other oblique datasets in the same session.
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997: See 3dWarp -help for details.
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997:++ Oblique dataset:/mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_localizer_task_objectcategories_run_1_wf/bold_reference_wf/gen_ref/slice.nii.gz is 9.173804 degrees from plumb.
180605-03:23:46,678 interface INFO:
	 stderr 2018-06-05T03:23:46.677997:++ Coarse del was 10, replaced with 3

**Comment by chrisfilo** [comment] 2018-06-05 20:55
Does it actually crash?

**Comment by steanze** [comment] 2018-06-05 21:00
Yes, it does. It produces a crashlog

**Comment by steanze** [comment] 2018-06-05 21:02
*********------ CRASH LOG ------------------------------***********
Fatal Signal 11 (SIGSEGV) received
.......... recent internal history .........................................
-----THD_find_atr [5]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=452) to THD_set_atr
----THD_set_atr [4]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=623) to THD_set_float_atr
---THD_set_float_atr [3]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=633) to 3dvolreg main
+++THD_set_char_atr [3]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=651) from 3dvolreg main
++++THD_set_atr [4]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=498) from THD_set_char_atr
    THD_set_atr -- VOLREG_BASE_IDCODE
+++++THD_find_atr [5]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=408) from THD_set_atr
-----THD_find_atr [5]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=452) to THD_set_atr
----THD_set_atr [4]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=623) to THD_set_char_atr
---THD_set_char_atr [3]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=653) to 3dvolreg main
+++THD_set_char_atr [3]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=651) from 3dvolreg main
++++THD_set_atr [4]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=498) from THD_set_char_atr
    THD_set_atr -- VOLREG_BASE_NAME
+++++THD_find_atr [5]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=408) from THD_set_atr
-----THD_find_atr [5]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=452) to THD_set_atr
----THD_set_atr [4]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=623) to THD_set_char_atr
---THD_set_char_atr [3]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=653) to 3dvolreg main
+++THD_set_float_atr [3]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=631) from 3dvolreg main
++++THD_set_atr [4]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=498) from THD_set_float_atr
    THD_set_atr -- VOLREG_CENTER_BASE
+++++THD_find_atr [5]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=408) from THD_set_atr
-----THD_find_atr [5]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=452) to THD_set_atr
----THD_set_atr [4]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=623) to THD_set_float_atr
---THD_set_float_atr [3]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=633) to 3dvolreg main
+++THD_set_int_atr [3]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=641) from 3dvolreg main
++++THD_set_atr [4]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=498) from THD_set_int_atr
    THD_set_atr -- VOLREG_ROTCOM_NUM
+++++THD_find_atr [5]: {ENTRY (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=408) from THD_set_atr
-----THD_find_atr [5]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=452) to THD_set_atr
----THD_set_atr [4]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=623) to THD_set_int_atr
---THD_set_int_atr [3]: EXIT} (file=/build/afni-16.2.07~dfsg.1/src/thd_atr.c line=643) to 3dvolreg main
............................................................................
** Command line was:
3dvolreg -Fourier -twopass -1Dfile slice.1D -1Dmatrix_save slice.aff12.1D -prefix slice_volreg.nii.gz -zpad 4 -maxdisp1D slice_md.1D /mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_localizer_task_objectcategories_run_1_wf/bold_reference_wf/gen_ref/slice.nii.gz
............................................................................
  3dvolreg main
** Command line was:
3dvolreg -Fourier -twopass -1Dfile slice.1D -1Dmatrix_save slice.aff12.1D -prefix slice_volreg.nii.gz -zpad 4 -maxdisp1D slice_md.1D /mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_localizer_task_objectcategories_run_1_wf/bold_reference_wf/gen_ref/slice.nii.gz
** AFNI compile date = Jun 12 2017
** [[Precompiled binary Debian-x86_64-1-gnu: Jun 12 2017]]
** Program Crash **

**Comment by steanze** [comment] 2018-06-05 21:07
Once we get this all sorted, with permission from the original authors we can make available the dataset in format compatible with fmriprep.

**Comment by steanze** [comment] 2018-06-08 18:19
It seems we are having the same problem of this dataset: https://openneuro.org/datasets/ds001145/versions/00001
We get the error despite we are not running slice timing correction (we use the flag --ignore slicetiming). What do you suggest? Should we include an empty "SliceTiming" field in the json?

**Comment by effigies** [comment] 2018-06-08 18:23
> Should we include an empty "SliceTiming" field in the json?

No, an invalid `SliceTiming` field will not help. I can't remember off the top of my head whether we'll crash or display a warning.

This appears to be during reference file generation, not slice timing correction, in any event. What is the exact command you're running for ds001145? If you can narrow it down to a specific subject, we may be able to reproduce this quickly on OpenNeuro.

**Comment by steanze** [comment] 2018-06-08 18:38
Thanks for the quick response! I did not run myself the analysis on ds001145. I am running fmriprep to preprocess the studyforrest data (http://studyforrest.org/). I have changed the folder structure of studyforrest so that it is BIDS compatible, and it now passes BIDS validation. I report below the full command I am running on the forrest dataset.

On ds001145 they report this warning: "You should define 'SliceTiming' for this file." which we also get on the studyforrest dataset, and fmriprep crashes for them too (under "Analyses"). So I'm hoping that if we can get fmriprep to work on ds001145, we might be able to get it to run on the studyforrest data too.

We'll run fmriprep with the latest version on ds001145 to make it easier to reproduce the issue. I only see a v1 for ds001145 on OpenNeuro. Do you have a link to access v3? This way I can try to run fmriprep directly on v3. Thanks so much!!

#!/bin/bash
participant="sub-18"
echo "participant: $participant"
exp_path="/mindhive/saxelab3/anzellotti/forrest"
sourcedir="${exp_path}/forrest_bids"
outdir="${exp_path}/derivatives"
workdir="${exp_path}/work"
module add openmind/singularity/2.4.5
cwd=/mindhive/saxelab3/anzellotti/software/preproc_fmriprep
DOW="Tue"
# SINGSCRATCH="/om/scratch//anzellot/fmriprep"
SINGSCRATCH="${exp_path}/scratch_singularity/fmriprep"
if [ ! -d "$SINGSCRATCH" ]; then
	mkdir -p "${SINGSCRATCH}"
fi
export SINGULARITY_CACHEDIR="${SINGSCRATCH}"
echo "FMRIPREP - Participant: ${participant}"
echo "experiment path:        ${exp_path}"
cd "${exp_path}" || exit
echo "output path:            ${outdir}"
cd "${outdir}" || exit
echo "source path:            ${sourcedir}"
cd "${sourcedir}" || exit
echo "work path:              ${workdir}"
cd "${cwd}" || exit
echo "Launching SingCon in:   ${cwd}"
echo ''
# echo 'COMMAND BEING RUN: '

singularity exec -B /mindhive/saxelab3/anzellotti:/mindhive/saxelab3/anzellotti docker://poldracklab/fmriprep:latest bash -c \
"ldconfig && \
fmriprep \
--participant_label ${participant} \
--nthreads 16 \
--omp-nthreads 16 \
--mem_mb 200000 \
--fs-no-reconall
--ignore slicetiming \
--bold2t1w-dof 9 \
--output-space T1w template fsnative fsaverage \
--template MNI152NLin2009cAsym \
--write-graph \
-w ${workdir} \
${sourcedir} \
${outdir} \
participant"
echo ''
echo 'sbatchrun FINISHED. exiting.'
exit

**Comment by effigies** [comment] 2018-06-08 18:47
Okay, thanks for that command. I'll see if I can run the equivalent on v3. (We're contacting the author to see whether it can be made public.)

**Comment by effigies** [comment] 2018-06-08 18:48
Oh, wait, your command seems to be for Study Forrest. Is there a specific subject that fails for ds001145, or will any one do?

**Comment by effigies** [comment] 2018-06-08 18:53
Hi, sorry, I'm apparently very bad at reading, today. So the only connection with ds001145 is that they also don't have slice timing correction? That's not a problem. In the absence of `'SliceTiming'`, fMRIPrep will simply skip the step, even if you don't specify `--ignore slicetiming`.

From what I can see, the issue is the performance of 3dVolreg on the first volumes of a BOLD series. If you can make the specific BOLD series available, we should be able to reproduce the issue.

**Comment by steanze** [comment] 2018-06-08 18:56
No problem :) Yes, ok, I will make the BOLD series available.

**Comment by steanze** [comment] 2018-06-08 19:22
The data should be available now. Let me know if you have any issues accessing them, and thanks again for the help.

**Comment by effigies** [comment] 2018-06-08 19:37
Thanks. I'm not on a great connection right now, so I might not get to try this out until Monday. And to confirm, you've tried this with which versions of fMRIPrep?

**Comment by steanze** [comment] 2018-06-08 19:43
Of course, no problem. This was run with fMRIPrep version 1.0.11 We can run it with other versions too if it can help.

**Comment by effigies** [comment] 2018-06-08 19:49
It would be good just to verify it's still an issue on 1.1.1 (released yesterday). I don't think anything we've changed since then should affect it, but if I'm unable to reproduce, it would be worth knowing exactly what's different.

I'll try with 1.0.11 and 1.1.1.

**Comment by steanze** [comment] 2018-06-08 19:55
Ok, we will run it with 1.1.1 as well and keep you posted.

**Comment by steanze** [comment] 2018-06-08 21:39
We ran it with 1.1.1 and it produced an error message too, I included the output log in the dropbox folder as it's too long to paste here. I paste here an excerpt of the log with some of the errors:

[Node] Error on "fmriprep_wf.single_subject_18_wf.func_preproc_ses_movie_task_movie_run_4_wf.bold_reference_wf.validate" (/mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_movie_task_movie_run_4_wf/bold_reference_wf/validate)
180608-20:41:29,97 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_18_wf.func_preproc_ses_movie_task_movie_run_1_wf.bold_reference_wf.validate" (/mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_movie_task_movie_run_1_wf/bold_reference_wf/validate)
180608-20:41:29,115 workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180608-20:41:29,122 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_18_wf.func_preproc_ses_localizer_task_retmapexpcon_run_1_wf.bold_reference_wf.validate" (/mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_localizer_task_retmapexpcon_run_1_wf/bold_reference_wf/validate)
180608-20:41:29,126 workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180608-20:41:29,128 workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180608-20:41:29,131 workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180608-20:41:29,136 workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180608-20:41:29,136 workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180608-20:41:29,139 workflow INFO:
	 [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
180608-20:41:29,139 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_18_wf.func_preproc_ses_movie_task_movie_run_2_wf.bold_reference_wf.validate" (/mindhive/saxelab3/anzellotti/forrest/work/fmriprep_wf/single_subject_18_wf/func_preproc_ses_movie_task_movie_run_2_wf/bold_reference_wf/validate)

**Comment by oesteban** [comment] 2018-06-08 22:08
One sec. [If this is correct](https://github.com/poldracklab/fmriprep/issues/1155#issuecomment-393993551):

```
find sub-16 -name '*_bold.json' -exec grep RepetitionTime "{}" +
sub-16/func/sub-16_ses-localizer_task-movielocalizer_run-1_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-localizer_task-objectcategories_run-1_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-localizer_task-objectcategories_run-2_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-localizer_task-objectcategories_run-3_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-localizer_task-objectcategories_run-4_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-localizer_task-retmapccw_run-1_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-localizer_task-retmapclw_run-1_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-localizer_task-retmapexp_run-1_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-localizer_task-retmapexpcon_run-1_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-movie_task-movie_run-1_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-movie_task-movie_run-2_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-movie_task-movie_run-3_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-movie_task-movie_run-4_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-movie_task-movie_run-5_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-movie_task-movie_run-6_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-movie_task-movie_run-7_bold.json: "RepetitionTime": 2000.00061035156,
sub-16/func/sub-16_ses-movie_task-movie_run-8_bold.json: "RepetitionTime": 2000.00061035156,
```

this is saying that the TR is 2000 seconds!. In BIDS, times are specified in seconds so I guess that should read just `2.0`. Could you check for this?

**Comment by steanze** [comment] 2018-06-11 17:48
Ok, thanks a lot for checking. We will see if we can resolve the issue on our end. Could you share with us the fmriprep command you ran? Thanks!

**Comment by effigies** [comment] 2018-06-11 17:53
```
fmriprep-docker $DATA $OUT participant \
    -w $SCRATCH \
    --fs-license-file $LICENSE \
    --fs-no-reconall \
    -t retmapclw
```

The last was just to pick a specific BOLD series that failed. I tested on both 1.0.11 and 1.1.1.

**Comment by steanze** [comment] 2018-06-11 17:56
Great, thanks!!

**Comment by effigies** [comment] 2018-07-25 15:34
Hi @steanze was your issue resolved?

**Comment by steanze** [comment] 2018-07-26 13:53
Hi @effigies ! Thanks for checking - we experienced some issues running fmriprep from the docker but we resolved them by generating a singularity image (.simg) from the docker container and running fmriprep from the .simg. So now everything is going smoothly.

**Comment by effigies** [comment] 2018-07-26 13:57
Great! Closing for now. Please reopen or open a new issue if you have further problems.

**Closed by effigies** 2018-07-26 13:57 UTC
